export const loremIpsum = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac metus vel turpis ultrices bibendum volutpat id nulla. Mauris pretium lectus eget nisi lacinia iaculis. Ut at gravida ante, vel egestas ex. Proin vestibulum eros vel velit venenatis, et sagittis velit porttitor. Suspendisse tempus orci a metus posuere ullamcorper. Proin volutpat metus auctor, imperdiet orci ornare, ultricies nibh. Pellentesque nec fermentum erat. Quisque lacinia id diam vitae ornare. Donec in luctus nisi. Etiam et convallis orci. Fusce et tortor semper, sodales lacus vitae, lobortis sapien. Aliquam facilisis tincidunt ligula vitae finibus. Proin ut erat elementum, interdum turpis vitae, rhoncus ipsum.",

  "Nulla rhoncus quam non augue rhoncus blandit. Fusce sed orci quis magna pulvinar tristique. Nullam at gravida mauris. Nullam a faucibus odio. Nulla auctor risus a nisl eleifend, ullamcorper placerat lectus malesuada. Nullam finibus bibendum neque ut auctor. Sed quis ultrices eros, eget vestibulum lectus. Etiam risus sapien, rhoncus in dui a, tincidunt posuere leo. Duis tempor imperdiet posuere. Curabitur posuere massa vitae neque blandit consequat.",

  "Quisque euismod consectetur eros, eget dapibus quam imperdiet a. Mauris non vulputate ante. Duis ullamcorper tempus mauris eu pretium. Phasellus vehicula arcu sed augue varius malesuada. In hac habitasse platea dictumst. Nunc ac sapien sed ante volutpat sagittis. Curabitur mi mauris, feugiat in nibh tincidunt, iaculis volutpat orci. Etiam eget fermentum ex. Donec porta risus ac orci faucibus, nec iaculis sem tincidunt. Sed dui est, interdum eu arcu sed, venenatis tristique orci. Aenean aliquet fermentum diam, id bibendum turpis vulputate eget. Vivamus cursus metus ut nisi ornare, eu tempor massa sagittis. Aliquam vitae nisl semper, gravida massa fermentum, laoreet urna. Vivamus luctus, sapien sagittis volutpat aliquam, dui augue posuere velit, sit amet sollicitudin risus lacus nec urna. Sed mattis nunc id mattis condimentum. Etiam quis ligula ultricies, ullamcorper risus eu, suscipit neque.",

  "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed vel maximus velit. Duis sodales metus at nibh euismod iaculis in sed purus. Quisque sagittis vel ex tempor consequat. Nam dapibus laoreet velit lobortis aliquam. Morbi lacus odio, tristique ut tincidunt et, dictum et ex. Duis lacus tellus, porttitor non porta ut, interdum eget ante. Donec vitae dignissim arcu.",

  "Nam et dui nec elit malesuada maximus. In eleifend finibus luctus. Phasellus ac quam ut augue tempor dapibus. Ut hendrerit, purus vel venenatis finibus, mi leo porta lorem, non pulvinar purus enim id ante. Cras a tellus at metus tristique pulvinar. Donec vitae dui non lectus porta efficitur sed a nisi. Nunc non est diam. Ut posuere justo vitae eros pharetra porta. Phasellus nec tincidunt nulla, sed volutpat augue.",

  "Duis elit tellus, pharetra nec ante nec, molestie ultrices elit. Quisque pulvinar ex nec ante dictum, eget mollis ante eleifend. Integer nisl nibh, scelerisque sit amet nunc eu, pulvinar laoreet risus. Maecenas sit amet convallis libero. Maecenas in fringilla quam, id mattis neque. Ut porta est a diam laoreet luctus. Nulla iaculis non mi quis iaculis. Donec nec fermentum ipsum. Nullam facilisis scelerisque erat, eu pretium purus varius at. Fusce accumsan, diam finibus vulputate laoreet, orci nulla pharetra mi, vel euismod augue magna ac erat. Etiam convallis arcu nec fringilla posuere.",

  "Nulla auctor semper leo at varius. Maecenas sodales tristique massa, et sodales nulla ullamcorper aliquet. Nulla facilisi. Aliquam elementum nunc eu nulla vestibulum pretium. Sed id nisi erat. Proin vel pretium felis. Aenean fermentum a libero id congue.",

  "Quisque fringilla sapien metus, et auctor ligula consectetur sit amet. Donec et ultrices purus. Donec sit amet lobortis velit. Proin auctor a sapien et egestas. Fusce neque est, mollis quis cursus et, efficitur id lorem. Nulla placerat nibh a mauris viverra faucibus. Phasellus maximus libero ac convallis mattis. Etiam cursus et turpis vel varius. Integer congue, neque in lobortis venenatis, enim felis pretium lacus, vel efficitur urna velit eu lectus. Curabitur eget elementum risus, et vulputate arcu. Sed sit amet leo facilisis, tincidunt nisl id, consequat urna. In tempus consectetur nibh non aliquam. Pellentesque eget velit consequat ligula scelerisque feugiat. Nam ut arcu mauris. Sed sed pellentesque ex, vitae auctor dui. Proin venenatis tempus odio eget rutrum.",

  "Fusce et urna suscipit, ultrices enim id, lobortis diam. Vivamus ullamcorper, velit in dignissim laoreet, arcu velit viverra velit, a accumsan tortor enim a nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur non tempus ipsum. Duis faucibus nec nunc ut congue. Praesent vitae ipsum nisi. Donec ultricies nec orci vitae laoreet. Donec in ex nulla. Nunc vitae porta metus. Curabitur volutpat nibh urna, in sodales leo tincidunt eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis id arcu et elit cursus volutpat.",

  "Morbi porta, sem eget rutrum sodales, lacus felis mollis magna, at placerat lorem turpis ac nunc. Pellentesque et elit congue, vulputate ligula vitae, posuere dolor. Ut ac arcu turpis. Aliquam ullamcorper neque sed magna fermentum ullamcorper. Phasellus consequat, lacus in posuere ullamcorper, arcu lectus lacinia arcu, a rutrum nisl velit venenatis lorem. Mauris ut aliquam ipsum. Nam in gravida nunc. Vivamus non sodales arcu, at pulvinar urna. Nunc metus nunc, auctor eu metus at, tempus posuere diam. Donec vitae ligula nibh.",

  "Sed eu turpis ut enim maximus imperdiet. Nunc sed libero nibh. Proin vehicula purus non quam euismod, eget tristique risus tempor. Integer sit amet neque tempor, feugiat est sit amet, maximus risus. Curabitur vitae dolor eros. Aliquam erat volutpat. Cras quis congue tellus.",

  "Donec tincidunt massa vel mi fermentum bibendum ac id nulla. Curabitur tristique purus et ligula rhoncus congue. Pellentesque ullamcorper orci tempus, eleifend sem quis, feugiat ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse potenti. In tellus neque, elementum in vehicula eget, eleifend non sem. Proin egestas fermentum purus, sit amet euismod magna molestie nec. Curabitur viverra dui quis sollicitudin scelerisque. Nulla ultricies bibendum pretium. Suspendisse scelerisque arcu dui, cursus lobortis libero sollicitudin sed. Vivamus ullamcorper arcu vitae lectus volutpat, condimentum egestas sapien ultrices.",

  "In dictum rhoncus augue, vel feugiat lectus facilisis non. Vivamus pulvinar nec magna vel facilisis. Suspendisse enim nulla, mollis a enim vel, interdum porttitor tortor. Fusce nec tellus id elit posuere laoreet. Nulla non lacus et risus tempus tempor eget nec odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque convallis felis a nisl pharetra porttitor. Sed ante lectus, imperdiet nec lacus in, tincidunt convallis ex.",

  "Sed blandit diam nisi, id placerat urna lobortis eu. Nunc quis consectetur arcu. Praesent sodales dui nec dui dignissim, ullamcorper rutrum diam consequat. Cras aliquet, est non gravida sollicitudin, arcu tellus lacinia velit, a blandit diam justo nec ex. Nunc mauris leo, sollicitudin a malesuada sit amet, maximus eget sapien. Suspendisse in consectetur ipsum, non porta nisl. Donec commodo semper rutrum.",

  "Suspendisse mattis vehicula mattis. Aliquam rhoncus libero nec tincidunt varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque ac magna et mi efficitur vulputate bibendum finibus turpis. Nunc hendrerit dui libero, eu ornare mauris faucibus nec. Cras augue urna, pharetra et ultricies vel, facilisis eu metus. Morbi venenatis augue ut mattis scelerisque. Duis at egestas odio. Nullam pellentesque, ex eu commodo efficitur, dui massa accumsan turpis, et pulvinar enim quam at lacus. Suspendisse sagittis magna nulla, non interdum odio tristique vitae. Vestibulum sit amet eleifend elit, sed euismod lorem. In a arcu vel lorem eleifend ornare sit amet eget libero. Proin sollicitudin vulputate rhoncus. Sed quis libero rhoncus, porta purus ac, rhoncus magna. Nunc ac velit lectus. Suspendisse dui nibh, convallis ac mattis eget, porttitor et turpis.",
];
